version: '3.8'

services:
  db:
    build: ./postgres/
    container_name: postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - webnet

  vault:
    build: ./vault/
    depends_on:
      - db
    container_name: vault_container
    ports:
      - "8200:8200"
    env_file:
      - .env
    volumes:
      - setup:/setup/
    networks:
      - webnet

  web:
    build: ./django/
    depends_on:
      - vault
    container_name: django_container
    volumes:
      - .:/app
      - setup:/setup/
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - webnet

  nginx:
    build: ./nginx/
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
    networks:
      - webnet
    depends_on:
      - web

volumes:
  postgres_data:
  setup:

networks:
  webnet:
