version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - webnet

  vault:
    build: ./vault/
    depends_on:
      - db
    container_name: vault_container
    expose:
      - "8200"
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - webnet

  web:
    build: ./django/
    depends_on:
      - vault
    container_name: django_container
    command: >
      sh -c "
        python -m pip install Pillow &&
        pip install django-cors-headers &&    
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py createsuperuser --no-input &&
        python manage.py runserver 0.0.0.0:8000" 
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
    expose:
      - "8000"
    networks:
      - webnet

  nginx:
    build: ./nginx/
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
    networks:
      - webnet
    depends_on:
      - web

volumes:
  postgres_data:

networks:
  webnet:
