version: '3.0'

services:
  db:
    build: ./postgres/
    container_name: postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - "5432"
    networks:
      - webnet

  vault:
    build: ./vault/
    depends_on:
      - db
    container_name: vault_container
    expose:
      - "8200"
    env_file:
      - .env
    volumes:
      - setup:/setup/
    networks:
      - webnet

  web:
    build: ./django/
    depends_on:
      - vault
    container_name: django_container
    volumes:
      - .:/app
      - setup:/setup/
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - webnet

  nginx-modsecurity:
    build: ./nginx-modsecurity/
    depends_on:
      - web
    container_name: nginx_container
    ports:
      - "1080:1080"
      - "1443:1443"
    volumes:
      - .:/app
    networks:
      - webnet

volumes:
  postgres_data:
  setup:

networks:
  webnet:
