version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"

  web:
    build: .
    container_name: django_container
    #command: >
     # sh -c "
       # python manage.py makemigrations &&
       # python manage.py migrate &&
       # python manage.py shell -c 'import os; from django.contrib.auth import get_user_model; User = get_user_model(); if not User.objects.filter(username=os.environ.get(\"DJANGO_SUPERUSER_USERNAME\")).exists(): User.objects.create_superuser(os.environ.get(\"DJANGO_SUPERUSER_USERNAME\"), os.environ.get(\"DJANGO_SUPERUSER_EMAIL\"), os.environ.get(\"DJANGO_SUPERUSER_PASSWORD\"))' &&
       # python manage.py runserver 0.0.0.0:8000"           # pip install djangorestframework # python manage.py collectstatic -may necessary
    command: >
      sh -c "
        python -m pip install Pillow &&
        pip install django-cors-headers && 
        pip install channels &&  
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py createsuperuser --no-input &&
        python manage.py runserver 0.0.0.0:8000" 
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}

      

volumes:
  postgres_data:
