# Generated by Django 4.2.14 on 2024-08-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_match_earned_points_match_mode_match_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='nick',
            field=models.CharField(default='Please select a nick', max_length=50),
        ),
    ]
