# Generated by Django 4.2.14 on 2024-08-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_playerprofile_image_alter_playerprofile_nick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprofile',
            old_name='image',
            new_name='userpic',
        ),
    ]
