# Generated by Django 4.2.14 on 2024-08-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_image_playerprofile_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='userpic',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
