# Generated by Django 4.2.17 on 2024-12-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_playerprofile_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='userpic',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='static/images'),
        ),
    ]
